### ISSUE TITLE
Issue using :Updatedocs

### ISSUE THREAD

**Issue by care2bfree** [sluosapher/VimAssist#1]
Note that I bolded what appears to me to be sigificant.
I'm getting the following error:
:Updatedocs
Do you want to use the directory /home/canderso to update the documentation?

Please provide the directory to use: /home/canderso/Documents/aiPDFsdoc_dir: /ho
me/canderso/Documents/aiPDFs
Expected a non-empty value for `assistant_id` but received None
Failed to retrieve the assistant with ID None. Creating a new assistant.
Error code: 400 - {'error': {'message': **"Invalid value: 'retrieval'. Supported v
alues are: 'code_interpreter', 'function', and 'file_search'."**, 'type': 'invalid
_request_error', 'param': 'tools[1].type', 'code': 'invalid_value'}}
Documentation update failed
Press ENTER or type command to continue

**Comment by care2bfree** [comment]
Actually there is a deeper issue that I found - I'm getting:
Error code: 400 - {'error': {'message': "The requested model 'gpt-4-turbo-previe
w' does not exist.", 'type': 'invalid_request_error', 'param': 'model', 'code':
'model_not_found'}}

I am investigating this problem now.

**Comment by care2bfree** [comment]
I succeeded in getting access to gpt-4-turbo-preview. Now the :Updatedocs does create the assistant but spits out another error:
Error detected while processing function vimassist#UpdateDocs:
line   40:
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "/home/canderso/.vim/pack/vimassist/start/VimAssist/autoload/../scripts/c
ommand_functions.py", line 97, in update_docs
    status = assistant_tools.update_files_of_assistant(assistant_id, file_id_lis
t)
  File "/home/canderso/.vim/pack/vimassist/start/VimAssist/autoload/../scripts/a
ssistant_tools.py", line 95, in update_files_of_assistant
    old_file_ids = assistant.file_ids
  File "/home/canderso/.local/lib/python3.10/site-packages/pydantic/main.py", li
ne 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item
!r}')
AttributeError: 'Assistant' object has no attribute 'file_ids'

Note that I did have to change the assistant tools.type value in your code from "retrieval" to "file_search" to get the command :Updatedocs to get this far. 
Since the first command I need to run cannot finish without changing the code, I'm wondering if this is an indication that the entire project code needs to be updated before attempting to use it?

**Comment by sluosapher** [comment]
The code works on my computer, which uses older openai library (1.10.0). But I recreated your error after I switched to the newest version of the library (1.23.6). It looks OpenAI changed the library interface.  Unfortunately, I did not specify the version of openai to be installed in the requirement file. I will look into the problem. Meantime, you can test the tools with openai library 1.10.0. I will update the requirement file as well.

**Comment by care2bfree** [comment]
Thanks! That's a big help to know about the library version. I will see what I can do about switching to the 1.10.0 version for a test.

**Comment by sluosapher** [comment]
updated the code.
